name: sudoku
channels:
  - conda-forge
  - defaults
dependencies:
  - black=23.3.0
  - flake8=6.0.0
  - ipython=8.15.0
  - line_profiler=4.1.1
  - numpy=1.26.0
  - pre-commit=3.4.0
  - pytest=7.4.0
  - python=3.11.5
  - virtualenv=20.17.1
